# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cbc284b4617d2411edb26bd00ed3c1948cd4c0ffae4d761f3965b2a2db24a7315da1ee8d988644557ba6e0a9bdaed2bd6e7a8592c0da04ca40c32bb1f101ca5

test:
  secret_key_base: 3eec54c01646ac634e4ff5611562d6a636e0de12f7fdff354128eed09eacac665c1203151ec81d58fa0f1b91417f29e0d704cbdf2827c431dcf24cb5438ee5f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
